### ISSUE TITLE
No data displayed in the FTC Dashboard

### ISSUE THREAD

**Issue by cybertractorchallenge** [acmerobotics/road-runner-ftc#1]
This function in the JS is unable to actually show the data being generated by the lateral ramp regression tests. The data gets put in the JSON file but there is an error "Reduce of empty array with no initial value" in the JS console so I suspect the issue is actually in a function called by this one. Our JSON file actually does have data in it and we can provide that if needed if you cannot reproduce the issue. 

Let me know if you need more logs, our students have been banging their heads against the wall on this one. 

https://github.com/acmerobotics/road-runner-ftc/blob/389a7c9d50915a6637a5d395e74a4948b4a37ed0/web/tuning/common.ts#L452

<img width="1664" alt="image" src="https://github.com/acmerobotics/road-runner-ftc/assets/149415786/03dd1a48-fe0f-4e12-9915-a440dcc0c316">

**Comment by Aask42** [comment]
Totally opened this under the wrong account, commenting so this account gets the notice.

**Comment by rbrott** [comment]
The JSON file would be useful.

**Comment by FTC19415** [comment]
[lateral-ramp-1700008136492.json](https://github.com/acmerobotics/road-runner-ftc/files/13371372/lateral-ramp-1700008136492.json)

**Comment by rbrott** [comment]
`LateralRampLogger` is only intended for teams using dead wheels. Are you sure you're using dead wheels?

**Comment by rbrott** [comment]
Did you set the localizer (`localizer = new ...`) in the drive class? While I see data in the tuning file, there is no data from a perpendicular encoder.

**Comment by FTC19415** [comment]
Ohhh, it's in the drive class, ok. I thought it was in the tuning opmodes because right above it that's what it was talking about. I'll check that out and let you know if any other questions come up. Thank you so much!

**Comment by Aask42** [comment]
I can't even get localizer to instantiate, it looks like the issue may be in line 425 of Tuning.kt where the laterSum is directly looking to talk to the leftEncs and rightEncs, but in the TuningOpeModes.java, if we are doing the ThreeDeadWheelLocalizer, it never sets those variables, instead setting the perpEncs. I think this is part of the issue. Please advise.

**Comment by Aask42** [comment]
Nevermind, working with students to understand platform better. Will close issue and let you know if we have more issues.

**Comment by cybertractorchallenge** [comment]
Issue was confusion from our student on what tests are for which configurations.
