### ISSUE TITLE
Some confusion more than issue on OTOS Tuning 

### ISSUE THREAD

**Issue by BeeWrangler70** [acmerobotics/road-runner-ftc#10]
OTOS Heading Offset Tuner
copy the heading offset into line 38 of SparkFunOTOSDrive

OTOS Position Offset Tuner
copy the pose offset into line 38 of SparkFunOTOSDrive

I'm a bit confused or maybe not understanding where these values go.

The closest I come to line 38 is line 42
        // RR localizer note: These units are inches and radians.
        public SparkFunOTOS.Pose2D offset = new SparkFunOTOS.Pose2D(-.125, 0, Math.toRadians(89.3656));

My sensor is .125 inches left of center, it's mounted center of bot and it's not quite pointing at 90 degress.  Off just a tiny bit.

I think when I was doing the Offset tuning, I was using that number to change the 90 degrees I was using.  That is how I got to 89.3656.  So as I was driving along the wall the heading was basically staying at zero.

I have no clue where to set the OTOS Offset Tuner number.   I did the test about 10 times.  I was bouncing around between -157.85 and -157.75 so it seems consistent.  I'm just not sure what to change.

**Comment by rbrott** [comment]
That's an issue for https://github.com/jdhs-ftc/sparkfun-otos-quickstart

**Comment by BeeWrangler70** [comment]
Sorry, I will open a ticket in that spot.  Appreciate your help.

Kevin Vance
M: 612-532-0386
***@***.***
(Using mobile mail, please ignore any typos)
