### ISSUE TITLE
Support for non-integer encoder values

### ISSUE THREAD

**Issue by j5155** [acmerobotics/road-runner-ftc#6]
This is an extremely strange request, but the data from the SparkFun OTOS sensor module is returned in non-integer inches instead of the integer ticks that encoders return, which prevents the tuning opmodes from running on it. 
I managed to implement support for it in the Java side at https://github.com/jdhs-ftc/road-runner-ftc-otos (through some somewhat cursed hacks), but though the data appears accurate, the graph of it is extremely strange (stepped and looping??).  

I am assuming something in the Typescript code is assuming that the data is composed of integers, but I'm unfamiliar with Typescript and can't find the source of the issue.

A version of the quickstart that (at least in my limited testing) supports the OTOS for localization is here: https://github.com/jdhs-ftc/sparkfun-otos-quickstart 
I've also attached the ForwardRampLogger data I got using the OTOS.
[forward-ramp-1718681716947.json](https://github.com/user-attachments/files/15880398/forward-ramp-1718681716947.json)

**Comment by j5155** [comment]
Discussed on the FTC Discord here: https://discord.com/channels/225450307654647808/1246977443030368349/1246977445433970709

**Comment by j5155** [comment]
This is caused by the inverseOverflow function assuming integer for it's bit magic. Fixed in my fork by checking if the data elements are integers before running inverseOverflow

**Comment by rbrott** [comment]
Glad you figured it out. It does seem like you'll want more extensive changes to the tuning procedure (and the localizer interface as you've pointed out before).

**Comment by rbrott** [comment]
Work towards official OTOS support is tracked in #8.
